### ISSUE TITLE
Document related datasets in one file

### ISSUE THREAD

**Issue by hadley** [AndySouth/rnaturalearth#4]
e.g.

```R
#' World country polygons from Natural Earth.
#' 
#' @name countries
NULL

#' @format A \code{SpatialPolygonsDataFrame} with 177 elements
#' @source \url{http//www.naturalearthdata.com/download/}
#' @rdname coutries
"countries110"
```

Note that roxygen will automatically supply:

```R
#' @docType data
#' @keywords dataset
#' @usage data(countries50)
```

so you can drop them

**Comment by AndySouth** [comment]
Thanks, done, although is it possible to get e.g. `?countries110` to work ? 
I tried with `@aliases` but doesn't seem to

**Comment by hadley** [comment]
Yes. You shouldn't need to do anything extra (but you might need to build and reload the package)

**Comment by AndySouth** [comment]
Thanks, that worked.
