### ISSUE TITLE
Include code used to generate data files

### ISSUE THREAD

**Issue by hadley** [AndySouth/rnaturalearth#8]
Perhaps using `devtools::use_raw_data()` convention?

(Judging from one of your comments, it looks like `stringsAsFactors != FALSE` in your loading code)

**Comment by AndySouth** [comment]
Moved into data-raw as suggested 8a615230fa7f0da2ff454170d0c557aba38f9e43 & 8d0bdb668422a48eb067e64cf67a36988f0184cf

stringsAsFactors set to FALSE d95856e2f7e26cbb08a1ac6d530cfd33c847e468
